from PyQt5 import QtCore, QtGui, QtWidgets

from Interface.CheckCombobox import CheckCombobox
from Interface.MplCanvas import MplCanvas


class PageLasso(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_12")
        self.verticalLayout_33 = QtWidgets.QHBoxLayout(self)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.tabWidget_lasso = QtWidgets.QTabWidget(self)
        self.tabWidget_lasso.setFont(font)
        self.tabWidget_lasso.setObjectName("tabWidget_lasso")
        self.tab_9 = QtWidgets.QWidget(flags=QtCore.Qt.Widget)
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_choose_x_lasso = QtWidgets.QLabel(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_lasso.sizePolicy().hasHeightForWidth())
        self.label_choose_x_lasso.setSizePolicy(size_policy)
        self.label_choose_x_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_x_lasso.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_x_lasso.setFont(font)
        self.label_choose_x_lasso.setObjectName("label_choose_x_lasso")
        self.verticalLayout_34.addWidget(self.label_choose_x_lasso)

        self.combobox_x_lasso = CheckCombobox()

        self.verticalLayout_34.addWidget(self.combobox_x_lasso)

        self.label_chosen_lasso = QtWidgets.QLabel(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_chosen_lasso.sizePolicy().hasHeightForWidth())
        self.label_chosen_lasso.setSizePolicy(size_policy)
        self.label_chosen_lasso.setMinimumSize(QtCore.QSize(0, 30))
        self.label_chosen_lasso.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_chosen_lasso.setFont(font)
        self.label_chosen_lasso.setObjectName("label_x_lasso_choose")
        self.verticalLayout_34.addWidget(self.label_chosen_lasso)

        self.label_choose_y_lasso = QtWidgets.QLabel(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_lasso.sizePolicy().hasHeightForWidth())
        self.label_choose_y_lasso.setSizePolicy(size_policy)
        self.label_choose_y_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_y_lasso.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_y_lasso.setFont(font)
        self.label_choose_y_lasso.setObjectName("label_choose_y_lasso")
        self.verticalLayout_34.addWidget(self.label_choose_y_lasso)

        self.comboBox_y_lasso = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_y_lasso.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_y_lasso.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBox_y_lasso.setObjectName("comboBox_y_lasso")

        self.verticalLayout_34.addWidget(self.comboBox_y_lasso)

        self.label_alpha_lasso = QtWidgets.QLabel(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_alpha_lasso.sizePolicy().hasHeightForWidth())
        self.label_alpha_lasso.setSizePolicy(size_policy)
        self.label_alpha_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_alpha_lasso.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_alpha_lasso.setFont(font)
        self.label_alpha_lasso.setObjectName("label_alpha_lasso")
        self.verticalLayout_34.addWidget(self.label_alpha_lasso)

        self.lineEdit_alpha_lasso = QtWidgets.QLineEdit(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_alpha_lasso.sizePolicy().hasHeightForWidth())
        self.lineEdit_alpha_lasso.setSizePolicy(size_policy)
        self.lineEdit_alpha_lasso.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_alpha_lasso.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_alpha_lasso.setObjectName("lineEdit_alpha_lasso")
        self.verticalLayout_34.addWidget(self.lineEdit_alpha_lasso)

        self.label_data_predict_lasso = QtWidgets.QLabel(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_data_predict_lasso.sizePolicy().hasHeightForWidth())
        self.label_data_predict_lasso.setSizePolicy(size_policy)
        self.label_data_predict_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_data_predict_lasso.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_data_predict_lasso.setFont(font)
        self.label_data_predict_lasso.setObjectName("label_data_predict_lasso")
        self.verticalLayout_34.addWidget(self.label_data_predict_lasso)

        self.lineEdit_data_lasso = QtWidgets.QLineEdit(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_data_lasso.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_lasso.setSizePolicy(size_policy)
        self.lineEdit_data_lasso.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_data_lasso.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_data_lasso.setObjectName("lineEdit_data_lasso")
        self.verticalLayout_34.addWidget(self.lineEdit_data_lasso)

        self.label_result_lasso = QtWidgets.QLabel(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_result_lasso.sizePolicy().hasHeightForWidth())
        self.label_result_lasso.setSizePolicy(size_policy)
        self.label_result_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_result_lasso.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_result_lasso.setFont(font)
        self.label_result_lasso.setObjectName("label_result_lasso")
        self.verticalLayout_34.addWidget(self.label_result_lasso)

        self.btn_find_lasso = QtWidgets.QPushButton(self.tab_9)
        self.btn_find_lasso.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_find_lasso.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_find_lasso.setFont(font)
        self.btn_find_lasso.setStyleSheet(stl_btn)
        self.btn_find_lasso.setObjectName("btn_find_lasso")
        self.verticalLayout_34.addWidget(self.btn_find_lasso)

        self.label_mse_lasso = QtWidgets.QLabel(self.tab_9)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_mse_lasso.sizePolicy().hasHeightForWidth())
        self.label_mse_lasso.setSizePolicy(size_policy)
        self.label_mse_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_mse_lasso.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_mse_lasso.setFont(font)
        self.label_mse_lasso.setObjectName("label_mse_lasso")
        self.verticalLayout_34.addWidget(self.label_mse_lasso)
        self.horizontalLayout_32.addLayout(self.verticalLayout_34)
        self.canvas_lasso = MplCanvas(self)
        self.horizontalLayout_32.addWidget(self.canvas_lasso)
        self.tabWidget_lasso.addTab(self.tab_9, "")

        self.tab_10 = QtWidgets.QWidget(flags=QtCore.Qt.Widget)
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.tab_10)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_min_alpha_lasso = QtWidgets.QLabel(self.tab_10)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_min_alpha_lasso.sizePolicy().hasHeightForWidth())
        self.label_min_alpha_lasso.setSizePolicy(size_policy)
        self.label_min_alpha_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_min_alpha_lasso.setFont(font)
        self.label_min_alpha_lasso.setObjectName("label_min_alpha_lasso")
        self.verticalLayout_35.addWidget(self.label_min_alpha_lasso)

        self.lineEdit_min_alpha_lasso = QtWidgets.QLineEdit(self.tab_10)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_min_alpha_lasso.sizePolicy().hasHeightForWidth())
        self.lineEdit_min_alpha_lasso.setSizePolicy(size_policy)
        self.lineEdit_min_alpha_lasso.setObjectName("lineEdit_min_alpha_lasso")
        self.verticalLayout_35.addWidget(self.lineEdit_min_alpha_lasso)

        self.label_max_alpha_lasso = QtWidgets.QLabel(self.tab_10)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_max_alpha_lasso.sizePolicy().hasHeightForWidth())
        self.label_max_alpha_lasso.setSizePolicy(size_policy)
        self.label_max_alpha_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_max_alpha_lasso.setFont(font)
        self.label_max_alpha_lasso.setObjectName("label_max_alpha_lasso")
        self.verticalLayout_35.addWidget(self.label_max_alpha_lasso)

        self.lineEdit_max_alpha_lasso = QtWidgets.QLineEdit(self.tab_10)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_max_alpha_lasso.sizePolicy().hasHeightForWidth())
        self.lineEdit_max_alpha_lasso.setSizePolicy(size_policy)
        self.lineEdit_max_alpha_lasso.setObjectName("lineEdit_max_alpha_lasso")
        self.verticalLayout_35.addWidget(self.lineEdit_max_alpha_lasso)

        self.btn_find_best_alpha_lasso = QtWidgets.QPushButton(self.tab_10)
        self.btn_find_best_alpha_lasso.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_find_best_alpha_lasso.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_find_best_alpha_lasso.setFont(font)
        self.btn_find_best_alpha_lasso.setStyleSheet(stl_btn)
        self.btn_find_best_alpha_lasso.setObjectName("btn_find_best_alpha_lasso")
        self.verticalLayout_35.addWidget(self.btn_find_best_alpha_lasso)

        self.label_best_alpha_lasso = QtWidgets.QLabel(self.tab_10)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_best_alpha_lasso.sizePolicy().hasHeightForWidth())
        self.label_best_alpha_lasso.setSizePolicy(size_policy)
        self.label_best_alpha_lasso.setMinimumSize(QtCore.QSize(0, 60))
        self.label_best_alpha_lasso.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_best_alpha_lasso.setFont(font)
        self.label_best_alpha_lasso.setObjectName("label_best_alpha_lasso")
        self.verticalLayout_35.addWidget(self.label_best_alpha_lasso)

        self.label_best_result_alpha_lasso = QtWidgets.QLabel(self.tab_10)
        self.label_best_result_alpha_lasso.setFont(font)
        self.label_best_result_alpha_lasso.setObjectName("label_best_result_alpha_lasso")
        self.verticalLayout_35.addWidget(self.label_best_result_alpha_lasso)

        self.horizontalLayout_33.addLayout(self.verticalLayout_35)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.canvas_lasso_best = MplCanvas(self)
        self.verticalLayout_36.addWidget(self.canvas_lasso_best)
        self.canvas_lasso_best_mse = MplCanvas(self)
        self.verticalLayout_36.addWidget(self.canvas_lasso_best_mse)
        self.horizontalLayout_33.addLayout(self.verticalLayout_36)
        self.tabWidget_lasso.addTab(self.tab_10, "")
        self.verticalLayout_33.addWidget(self.tabWidget_lasso)
