from PyQt5 import QtCore, QtGui, QtWidgets

from Interface.CheckCombobox import CheckCombobox
from Interface.MplCanvas import MplCanvas


class PageQuadraticDiscriminant(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_16")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_choose_x_QuadraticDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_QuadraticDiscriminant.sizePolicy().hasHeightForWidth())
        self.label_choose_x_QuadraticDiscriminant.setSizePolicy(size_policy)
        self.label_choose_x_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.label_choose_x_QuadraticDiscriminant.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_choose_x_QuadraticDiscriminant.setFont(font)
        self.label_choose_x_QuadraticDiscriminant.setObjectName("label_choose_x_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.label_choose_x_QuadraticDiscriminant)
        self.combobox_x_QuadraticDiscriminant = CheckCombobox()

        self.verticalLayout_42.addWidget(self.combobox_x_QuadraticDiscriminant)
        self.chosen_x_QuadraticDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.chosen_x_QuadraticDiscriminant.sizePolicy().hasHeightForWidth())
        self.chosen_x_QuadraticDiscriminant.setSizePolicy(size_policy)
        self.chosen_x_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.chosen_x_QuadraticDiscriminant.setFont(font)
        self.chosen_x_QuadraticDiscriminant.setObjectName("chosen_x_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.chosen_x_QuadraticDiscriminant)
        self.label_choose_y_QuadraticDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_QuadraticDiscriminant.sizePolicy().hasHeightForWidth())
        self.label_choose_y_QuadraticDiscriminant.setSizePolicy(size_policy)
        self.label_choose_y_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.label_choose_y_QuadraticDiscriminant.setFont(font)
        self.label_choose_y_QuadraticDiscriminant.setObjectName("label_choose_y_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.label_choose_y_QuadraticDiscriminant)
        self.comboBox_y_QuadraticDiscriminant = QtWidgets.QComboBox(self)
        self.comboBox_y_QuadraticDiscriminant.setObjectName("comboBox_y_QuadraticDiscriminant")

        self.verticalLayout_42.addWidget(self.comboBox_y_QuadraticDiscriminant)
        self.label_data_predict_QuadraticDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_data_predict_QuadraticDiscriminant.sizePolicy().hasHeightForWidth())
        self.label_data_predict_QuadraticDiscriminant.setSizePolicy(size_policy)
        self.label_data_predict_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.label_data_predict_QuadraticDiscriminant.setFont(font)
        self.label_data_predict_QuadraticDiscriminant.setObjectName("label_data_predict_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.label_data_predict_QuadraticDiscriminant)
        self.lineEdit_data_QuadraticDiscriminant = QtWidgets.QLineEdit(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_data_QuadraticDiscriminant.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_QuadraticDiscriminant.setSizePolicy(size_policy)
        self.lineEdit_data_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_data_QuadraticDiscriminant.setObjectName("lineEdit_data_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.lineEdit_data_QuadraticDiscriminant)
        self.predict_QuadraticDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.predict_QuadraticDiscriminant.sizePolicy().hasHeightForWidth())
        self.predict_QuadraticDiscriminant.setSizePolicy(size_policy)
        self.predict_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.predict_QuadraticDiscriminant.setMaximumSize(QtCore.QSize(16777215, 40))
        self.predict_QuadraticDiscriminant.setFont(font)
        self.predict_QuadraticDiscriminant.setObjectName("predict_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.predict_QuadraticDiscriminant)
        self.btn_predict_QuadraticDiscriminant = QtWidgets.QPushButton(self)
        self.btn_predict_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_predict_QuadraticDiscriminant.setFont(font)
        self.btn_predict_QuadraticDiscriminant.setStyleSheet(stl_btn)
        self.btn_predict_QuadraticDiscriminant.setObjectName("btn_predict_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.btn_predict_QuadraticDiscriminant)
        self.report_QuadraticDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.report_QuadraticDiscriminant.sizePolicy().hasHeightForWidth())
        self.report_QuadraticDiscriminant.setSizePolicy(size_policy)
        self.report_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.report_QuadraticDiscriminant.setFont(font)
        self.report_QuadraticDiscriminant.setObjectName("report_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.report_QuadraticDiscriminant)
        self.accuracy_QuadraticDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.accuracy_QuadraticDiscriminant.sizePolicy().hasHeightForWidth())
        self.accuracy_QuadraticDiscriminant.setSizePolicy(size_policy)
        self.accuracy_QuadraticDiscriminant.setMinimumSize(QtCore.QSize(0, 60))
        self.accuracy_QuadraticDiscriminant.setFont(font)
        self.accuracy_QuadraticDiscriminant.setObjectName("accuracy_QuadraticDiscriminant")
        self.verticalLayout_42.addWidget(self.accuracy_QuadraticDiscriminant)

        self.horizontalLayout_37.addLayout(self.verticalLayout_42)
        self.canvas_QuadraticDiscriminant = MplCanvas(self)
        self.horizontalLayout_37.addWidget(self.canvas_QuadraticDiscriminant)
