from PyQt5 import QtCore, QtWidgets

from Interface.MplCanvas import MplCanvas


class PageNaturalCubicSpline(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_choose_x_NaturalCubicSpline = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_NaturalCubicSpline.sizePolicy().hasHeightForWidth())
        self.label_choose_x_NaturalCubicSpline.setSizePolicy(size_policy)
        self.label_choose_x_NaturalCubicSpline.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_x_NaturalCubicSpline.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_x_NaturalCubicSpline.setFont(font)
        self.label_choose_x_NaturalCubicSpline.setObjectName("label_choose_x_NaturalCubicSpline")
        self.verticalLayout_24.addWidget(self.label_choose_x_NaturalCubicSpline)
        self.comboBox_x_NaturalCubicSpline = QtWidgets.QComboBox(self)
        self.comboBox_x_NaturalCubicSpline.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_x_NaturalCubicSpline.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBox_x_NaturalCubicSpline.setObjectName("comboBox_x_NaturalCubicSpline")

        self.verticalLayout_24.addWidget(self.comboBox_x_NaturalCubicSpline)
        self.label_choose_y_NaturalCubicSpline = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_NaturalCubicSpline.sizePolicy().hasHeightForWidth())
        self.label_choose_y_NaturalCubicSpline.setSizePolicy(size_policy)
        self.label_choose_y_NaturalCubicSpline.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_y_NaturalCubicSpline.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_y_NaturalCubicSpline.setFont(font)
        self.label_choose_y_NaturalCubicSpline.setObjectName("label_choose_y_NaturalCubicSpline")
        self.verticalLayout_24.addWidget(self.label_choose_y_NaturalCubicSpline)
        self.comboBox_y_NaturalCubicSpline = QtWidgets.QComboBox(self)
        self.comboBox_y_NaturalCubicSpline.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_y_NaturalCubicSpline.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBox_y_NaturalCubicSpline.setObjectName("comboBox_y_NaturalCubicSpline")

        self.verticalLayout_24.addWidget(self.comboBox_y_NaturalCubicSpline)
        self.btn_predict_NaturalCubicSpline = QtWidgets.QPushButton(self)
        self.btn_predict_NaturalCubicSpline.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_predict_NaturalCubicSpline.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_predict_NaturalCubicSpline.setFont(font)
        self.btn_predict_NaturalCubicSpline.setStyleSheet(stl_btn)
        self.btn_predict_NaturalCubicSpline.setObjectName("btn_predict_NaturalCubicSpline")
        self.verticalLayout_24.addWidget(self.btn_predict_NaturalCubicSpline)
        self.label_rmse_NaturalCubicSpline = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_rmse_NaturalCubicSpline.sizePolicy().hasHeightForWidth())
        self.label_rmse_NaturalCubicSpline.setSizePolicy(size_policy)
        self.label_rmse_NaturalCubicSpline.setMinimumSize(QtCore.QSize(0, 60))
        self.label_rmse_NaturalCubicSpline.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_rmse_NaturalCubicSpline.setFont(font)
        self.label_rmse_NaturalCubicSpline.setObjectName("label_rmse_NaturalCubicSpline")
        self.verticalLayout_24.addWidget(self.label_rmse_NaturalCubicSpline)
        self.horizontalLayout_14.addLayout(self.verticalLayout_24)
        self.canvas_NaturalCubicSpline = MplCanvas(self)
        self.horizontalLayout_14.addWidget(self.canvas_NaturalCubicSpline)
