from PyQt5 import QtCore, QtGui, QtWidgets

from Interface.CheckCombobox import CheckCombobox
from Interface.MplCanvas import MplCanvas


class PageRidgeRegression(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_11")
        self.verticalLayout_30 = QtWidgets.QHBoxLayout(self)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.tabWidget_ridge = QtWidgets.QTabWidget(self)
        self.tabWidget_ridge.setFont(font)
        self.tabWidget_ridge.setObjectName("tabWidget_ridge")
        self.tab_7 = QtWidgets.QWidget(flags=QtCore.Qt.Widget)
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_choose_x_ridge = QtWidgets.QLabel(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_ridge.sizePolicy().hasHeightForWidth())
        self.label_choose_x_ridge.setSizePolicy(size_policy)
        self.label_choose_x_ridge.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_x_ridge.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_x_ridge.setFont(font)
        self.label_choose_x_ridge.setObjectName("label_choose_x_ridge")
        self.verticalLayout_31.addWidget(self.label_choose_x_ridge)
        self.combobox_x_ridge = CheckCombobox()
        self.verticalLayout_31.addWidget(self.combobox_x_ridge)
        self.label_chosen_ridge = QtWidgets.QLabel(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_chosen_ridge.sizePolicy().hasHeightForWidth())
        self.label_chosen_ridge.setSizePolicy(size_policy)
        self.label_chosen_ridge.setMinimumSize(QtCore.QSize(0, 30))
        self.label_chosen_ridge.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_chosen_ridge.setFont(font)
        self.label_chosen_ridge.setObjectName("label_x_ridge_choose")
        self.verticalLayout_31.addWidget(self.label_chosen_ridge)

        self.label_choose_y_ridge = QtWidgets.QLabel(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_ridge.sizePolicy().hasHeightForWidth())
        self.label_choose_y_ridge.setSizePolicy(size_policy)
        self.label_choose_y_ridge.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_y_ridge.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_y_ridge.setFont(font)
        self.label_choose_y_ridge.setObjectName("label_choose_y_ridge")
        self.verticalLayout_31.addWidget(self.label_choose_y_ridge)

        self.comboBox_y_ridge = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_y_ridge.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_y_ridge.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBox_y_ridge.setObjectName("comboBox_y_ridge")
        self.verticalLayout_31.addWidget(self.comboBox_y_ridge)

        self.label_alpha = QtWidgets.QLabel(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_alpha.sizePolicy().hasHeightForWidth())
        self.label_alpha.setSizePolicy(size_policy)
        self.label_alpha.setMinimumSize(QtCore.QSize(0, 60))
        self.label_alpha.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_alpha.setFont(font)
        self.label_alpha.setObjectName("label_alpha")
        self.verticalLayout_31.addWidget(self.label_alpha)

        self.lineEdit_alpha = QtWidgets.QLineEdit(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_alpha.sizePolicy().hasHeightForWidth())
        self.lineEdit_alpha.setSizePolicy(size_policy)
        self.lineEdit_alpha.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_alpha.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.verticalLayout_31.addWidget(self.lineEdit_alpha)

        self.label_data_predict_ridge = QtWidgets.QLabel(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_data_predict_ridge.sizePolicy().hasHeightForWidth())
        self.label_data_predict_ridge.setSizePolicy(size_policy)
        self.label_data_predict_ridge.setMinimumSize(QtCore.QSize(0, 60))
        self.label_data_predict_ridge.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_data_predict_ridge.setFont(font)
        self.label_data_predict_ridge.setObjectName("label_data_predict_PolynomialRegression")
        self.verticalLayout_31.addWidget(self.label_data_predict_ridge)

        self.lineEdit_data_ridge = QtWidgets.QLineEdit(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_data_ridge.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_ridge.setSizePolicy(size_policy)
        self.lineEdit_data_ridge.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_data_ridge.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_data_ridge.setObjectName("lineEdit_data_ridge")
        self.verticalLayout_31.addWidget(self.lineEdit_data_ridge)

        self.label_result_ridge = QtWidgets.QLabel(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_result_ridge.sizePolicy().hasHeightForWidth())
        self.label_result_ridge.setSizePolicy(size_policy)
        self.label_result_ridge.setMinimumSize(QtCore.QSize(0, 60))
        self.label_result_ridge.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_result_ridge.setFont(font)
        self.label_result_ridge.setObjectName("label_result_ridge")
        self.verticalLayout_31.addWidget(self.label_result_ridge)

        self.btn_find_ridge = QtWidgets.QPushButton(self.tab_7)
        self.btn_find_ridge.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_find_ridge.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_find_ridge.setFont(font)
        self.btn_find_ridge.setStyleSheet(stl_btn)
        self.btn_find_ridge.setObjectName("btn_find_ridge")
        self.verticalLayout_31.addWidget(self.btn_find_ridge)

        self.label_mse_ridge = QtWidgets.QLabel(self.tab_7)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_mse_ridge.sizePolicy().hasHeightForWidth())
        self.label_mse_ridge.setSizePolicy(size_policy)
        self.label_mse_ridge.setMinimumSize(QtCore.QSize(0, 60))
        self.label_mse_ridge.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_mse_ridge.setFont(font)
        self.label_mse_ridge.setObjectName("label_mse_ridge")
        self.verticalLayout_31.addWidget(self.label_mse_ridge)
        self.horizontalLayout_30.addLayout(self.verticalLayout_31)
        self.canvas_ridge = MplCanvas(self)
        self.horizontalLayout_30.addWidget(self.canvas_ridge)
        self.tabWidget_ridge.addTab(self.tab_7, "")

        self.tab_8 = QtWidgets.QWidget(flags=QtCore.Qt.Widget)
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_min_alpha = QtWidgets.QLabel(self.tab_8)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_min_alpha.sizePolicy().hasHeightForWidth())
        self.label_min_alpha.setSizePolicy(size_policy)
        self.label_min_alpha.setMinimumSize(QtCore.QSize(0, 60))
        self.label_min_alpha.setFont(font)
        self.label_min_alpha.setObjectName("label_min_alpha")
        self.verticalLayout_32.addWidget(self.label_min_alpha)
        self.lineEdit_min_alpha = QtWidgets.QLineEdit(self.tab_8)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_min_alpha.sizePolicy().hasHeightForWidth())
        self.lineEdit_min_alpha.setSizePolicy(size_policy)
        self.lineEdit_min_alpha.setObjectName("lineEdit_min_alpha")
        self.verticalLayout_32.addWidget(self.lineEdit_min_alpha)
        self.label_max_alpha = QtWidgets.QLabel(self.tab_8)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_max_alpha.sizePolicy().hasHeightForWidth())
        self.label_max_alpha.setSizePolicy(size_policy)
        self.label_max_alpha.setMinimumSize(QtCore.QSize(0, 60))
        self.label_max_alpha.setFont(font)
        self.label_max_alpha.setObjectName("label_max_alpha")
        self.verticalLayout_32.addWidget(self.label_max_alpha)
        self.lineEdit_max_alpha = QtWidgets.QLineEdit(self.tab_8)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_max_alpha.sizePolicy().hasHeightForWidth())
        self.lineEdit_max_alpha.setSizePolicy(size_policy)
        self.lineEdit_max_alpha.setObjectName("lineEdit_max_alpha")
        self.verticalLayout_32.addWidget(self.lineEdit_max_alpha)
        self.btn_find_best_alpha = QtWidgets.QPushButton(self.tab_8)
        self.btn_find_best_alpha.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_find_best_alpha.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_find_best_alpha.setFont(font)
        self.btn_find_best_alpha.setStyleSheet(stl_btn)
        self.btn_find_best_alpha.setObjectName("btn_find_best_alpha")
        self.verticalLayout_32.addWidget(self.btn_find_best_alpha)
        self.label_best_alpha = QtWidgets.QLabel(self.tab_8)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_best_alpha.sizePolicy().hasHeightForWidth())
        self.label_best_alpha.setSizePolicy(size_policy)
        self.label_best_alpha.setMinimumSize(QtCore.QSize(0, 60))
        self.label_best_alpha.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_best_alpha.setFont(font)
        self.label_best_alpha.setObjectName("label_best_alpha")
        self.verticalLayout_32.addWidget(self.label_best_alpha)
        self.label_best_result_alpha = QtWidgets.QLabel(self.tab_8)
        self.label_best_result_alpha.setFont(font)
        self.label_best_result_alpha.setObjectName("label_best_result_alpha")
        self.verticalLayout_32.addWidget(self.label_best_result_alpha)
        self.horizontalLayout_31.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.canvas_ridge_best = MplCanvas(self)
        self.verticalLayout_33.addWidget(self.canvas_ridge_best)
        self.canvas_ridge_best_mse = MplCanvas(self)
        self.verticalLayout_33.addWidget(self.canvas_ridge_best_mse)
        self.horizontalLayout_31.addLayout(self.verticalLayout_33)
        self.tabWidget_ridge.addTab(self.tab_8, "")
        self.verticalLayout_30.addWidget(self.tabWidget_ridge)
