from PyQt5 import QtCore, QtGui, QtWidgets

from Interface.CheckCombobox import CheckCombobox
from Interface.MplCanvas import MplCanvas


class PageKNNClassification(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget(flags=QtCore.Qt.Widget)
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_choose_x_knnClassification = QtWidgets.QLabel(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_knnClassification.sizePolicy().hasHeightForWidth())
        self.label_choose_x_knnClassification.setSizePolicy(size_policy)
        self.label_choose_x_knnClassification.setMinimumSize(QtCore.QSize(0, 40))
        self.label_choose_x_knnClassification.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_choose_x_knnClassification.setFont(font)
        self.label_choose_x_knnClassification.setObjectName("label_choose_x_knnClassification")
        self.verticalLayout_13.addWidget(self.label_choose_x_knnClassification)
        self.combobox_x_knnClassification = CheckCombobox()

        self.verticalLayout_13.addWidget(self.combobox_x_knnClassification)
        self.x_knnClassification = QtWidgets.QLabel(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.x_knnClassification.sizePolicy().hasHeightForWidth())
        self.x_knnClassification.setSizePolicy(size_policy)
        self.x_knnClassification.setMinimumSize(QtCore.QSize(0, 40))
        self.x_knnClassification.setMaximumSize(QtCore.QSize(16777215, 40))
        self.x_knnClassification.setFont(font)
        self.x_knnClassification.setObjectName("x_knnClassification")
        self.verticalLayout_13.addWidget(self.x_knnClassification)
        self.label_choose_y_knnClassification = QtWidgets.QLabel(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_knnClassification.sizePolicy().hasHeightForWidth())
        self.label_choose_y_knnClassification.setSizePolicy(size_policy)
        self.label_choose_y_knnClassification.setMinimumSize(QtCore.QSize(0, 40))
        self.label_choose_y_knnClassification.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_choose_y_knnClassification.setFont(font)
        self.label_choose_y_knnClassification.setObjectName("label_choose_y_knnClassification")
        self.verticalLayout_13.addWidget(self.label_choose_y_knnClassification)
        self.combobox_y_knnClassification = CheckCombobox()

        self.verticalLayout_13.addWidget(self.combobox_y_knnClassification)
        self.label_num_clas = QtWidgets.QLabel(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_num_clas.sizePolicy().hasHeightForWidth())
        self.label_num_clas.setSizePolicy(size_policy)
        self.label_num_clas.setMinimumSize(QtCore.QSize(0, 40))
        self.label_num_clas.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_num_clas.setFont(font)
        self.label_num_clas.setObjectName("label_num_clas")
        self.verticalLayout_13.addWidget(self.label_num_clas)
        self.lineEdit_num_class_knnClassification = QtWidgets.QLineEdit(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_num_class_knnClassification.sizePolicy().hasHeightForWidth())
        self.lineEdit_num_class_knnClassification.setSizePolicy(size_policy)
        self.lineEdit_num_class_knnClassification.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_num_class_knnClassification.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_num_class_knnClassification.setObjectName("lineEdit_num_class_knnClassification")
        self.verticalLayout_13.addWidget(self.lineEdit_num_class_knnClassification)
        self.range_clas = QtWidgets.QLabel(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.range_clas.sizePolicy().hasHeightForWidth())
        self.range_clas.setSizePolicy(size_policy)
        self.range_clas.setMinimumSize(QtCore.QSize(0, 40))
        self.range_clas.setMaximumSize(QtCore.QSize(16777215, 40))
        self.range_clas.setFont(font)
        self.range_clas.setObjectName("range_clas")
        self.verticalLayout_13.addWidget(self.range_clas)
        self.label_k_knnClassification = QtWidgets.QLabel(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(40)
        size_policy.setHeightForWidth(self.label_k_knnClassification.sizePolicy().hasHeightForWidth())
        self.label_k_knnClassification.setSizePolicy(size_policy)
        self.label_k_knnClassification.setMinimumSize(QtCore.QSize(0, 40))
        self.label_k_knnClassification.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_k_knnClassification.setFont(font)
        self.label_k_knnClassification.setObjectName("label_k_knnClassification")
        self.verticalLayout_13.addWidget(self.label_k_knnClassification)
        self.lineEdit_k_knnClassification = QtWidgets.QLineEdit(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_k_knnClassification.sizePolicy().hasHeightForWidth())
        self.lineEdit_k_knnClassification.setSizePolicy(size_policy)
        self.lineEdit_k_knnClassification.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_k_knnClassification.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_k_knnClassification.setObjectName("lineEdit_k_knnClassification")
        self.verticalLayout_13.addWidget(self.lineEdit_k_knnClassification)
        self.label_data_knnClassification = QtWidgets.QLabel(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_data_knnClassification.sizePolicy().hasHeightForWidth())
        self.label_data_knnClassification.setSizePolicy(size_policy)
        self.label_data_knnClassification.setMinimumSize(QtCore.QSize(0, 40))
        self.label_data_knnClassification.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_data_knnClassification.setFont(font)
        self.label_data_knnClassification.setObjectName("label_data_knnClassification")
        self.verticalLayout_13.addWidget(self.label_data_knnClassification)
        self.lineEdit_data_knnClassification = QtWidgets.QLineEdit(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_data_knnClassification.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_knnClassification.setSizePolicy(size_policy)
        self.lineEdit_data_knnClassification.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_data_knnClassification.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_data_knnClassification.setObjectName("lineEdit_data_knnClassification")
        self.verticalLayout_13.addWidget(self.lineEdit_data_knnClassification)
        self.result_predict_knnClassification = QtWidgets.QLabel(self.tab)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.result_predict_knnClassification.sizePolicy().hasHeightForWidth())
        self.result_predict_knnClassification.setSizePolicy(size_policy)
        self.result_predict_knnClassification.setMinimumSize(QtCore.QSize(0, 40))
        self.result_predict_knnClassification.setMaximumSize(QtCore.QSize(16777215, 40))
        self.result_predict_knnClassification.setFont(font)
        self.result_predict_knnClassification.setObjectName("result_predict_knnClassification")
        self.verticalLayout_13.addWidget(self.result_predict_knnClassification)
        self.btn_predict_knnClassification = QtWidgets.QPushButton(self.tab)
        self.btn_predict_knnClassification.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_predict_knnClassification.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_predict_knnClassification.setFont(font)
        self.btn_predict_knnClassification.setStyleSheet(stl_btn)
        self.btn_predict_knnClassification.setObjectName("btn_predict_knnClassification")
        self.verticalLayout_13.addWidget(self.btn_predict_knnClassification)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.canvas_knnClassification = MplCanvas(self)
        self.verticalLayout_12.addWidget(self.canvas_knnClassification)
        self.label_res_knn = QtWidgets.QLabel(self.tab)
        self.label_res_knn.setFont(font)
        self.label_res_knn.setObjectName("label_res_knn")
        self.verticalLayout_12.addWidget(self.label_res_knn)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget(flags=QtCore.Qt.Widget)
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_min_k_knnClassification = QtWidgets.QLabel(self.tab_2)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_min_k_knnClassification.sizePolicy().hasHeightForWidth())
        self.label_min_k_knnClassification.setSizePolicy(size_policy)
        self.label_min_k_knnClassification.setMinimumSize(QtCore.QSize(0, 60))
        self.label_min_k_knnClassification.setFont(font)
        self.label_min_k_knnClassification.setObjectName("label_min_k_knnClassification")
        self.verticalLayout_15.addWidget(self.label_min_k_knnClassification)
        self.lineEdit_min_k_knnClassification = QtWidgets.QLineEdit(self.tab_2)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_min_k_knnClassification.sizePolicy().hasHeightForWidth())
        self.lineEdit_min_k_knnClassification.setSizePolicy(size_policy)
        self.lineEdit_min_k_knnClassification.setObjectName("lineEdit_min_k_knnClassification")
        self.verticalLayout_15.addWidget(self.lineEdit_min_k_knnClassification)
        self.label_max_k_knnClassification = QtWidgets.QLabel(self.tab_2)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_max_k_knnClassification.sizePolicy().hasHeightForWidth())
        self.label_max_k_knnClassification.setSizePolicy(size_policy)
        self.label_max_k_knnClassification.setMinimumSize(QtCore.QSize(0, 60))
        self.label_max_k_knnClassification.setFont(font)
        self.label_max_k_knnClassification.setObjectName("label_max_k_knnClassification")
        self.verticalLayout_15.addWidget(self.label_max_k_knnClassification)
        self.lineEdit_max_k_knnClassification = QtWidgets.QLineEdit(self.tab_2)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_max_k_knnClassification.sizePolicy().hasHeightForWidth())
        self.lineEdit_max_k_knnClassification.setSizePolicy(size_policy)
        self.lineEdit_max_k_knnClassification.setObjectName("lineEdit_max_k_knnClassification")
        self.verticalLayout_15.addWidget(self.lineEdit_max_k_knnClassification)
        self.btn_find_best_k_knnClassification = QtWidgets.QPushButton(self.tab_2)
        self.btn_find_best_k_knnClassification.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_find_best_k_knnClassification.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_find_best_k_knnClassification.setFont(font)
        self.btn_find_best_k_knnClassification.setStyleSheet(stl_btn)
        self.btn_find_best_k_knnClassification.setObjectName("btn_find_best_k_knnClassification")
        self.verticalLayout_15.addWidget(self.btn_find_best_k_knnClassification)
        self.label_best_k_knnClassification = QtWidgets.QLabel(self.tab_2)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_best_k_knnClassification.sizePolicy().hasHeightForWidth())
        self.label_best_k_knnClassification.setSizePolicy(size_policy)
        self.label_best_k_knnClassification.setMinimumSize(QtCore.QSize(0, 60))
        self.label_best_k_knnClassification.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_best_k_knnClassification.setFont(font)
        self.label_best_k_knnClassification.setObjectName("label_best_k_knnClassification")
        self.verticalLayout_15.addWidget(self.label_best_k_knnClassification)
        self.label_best_result_knnClassification = QtWidgets.QLabel(self.tab_2)
        self.label_best_result_knnClassification.setFont(font)
        self.label_best_result_knnClassification.setObjectName("label_best_result_knnClassification")
        self.verticalLayout_15.addWidget(self.label_best_result_knnClassification)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.canvas_knnClassification_best = MplCanvas(self)
        self.verticalLayout_14.addWidget(self.canvas_knnClassification_best)
        self.canvas_knnClassification_best_matrix = MplCanvas(self)
        self.verticalLayout_14.addWidget(self.canvas_knnClassification_best_matrix)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
