from PyQt5 import QtCore, QtWidgets

from Interface.CheckCombobox import CheckCombobox


class PageMultipleLinearRegression(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_x_multy_regression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_x_multy_regression.sizePolicy().hasHeightForWidth())
        self.label_x_multy_regression.setSizePolicy(size_policy)
        self.label_x_multy_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_x_multy_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_x_multy_regression.setFont(font)
        self.label_x_multy_regression.setObjectName("label_x_multy_regression")
        self.verticalLayout_8.addWidget(self.label_x_multy_regression)
        self.combobox_x_multy_regression = CheckCombobox()

        self.verticalLayout_8.addWidget(self.combobox_x_multy_regression)
        self.label_chosen_multy = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_chosen_multy.sizePolicy().hasHeightForWidth())
        self.label_chosen_multy.setSizePolicy(size_policy)
        self.label_chosen_multy.setMinimumSize(QtCore.QSize(0, 30))
        self.label_chosen_multy.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_chosen_multy.setFont(font)
        self.label_chosen_multy.setObjectName("label_x_multy_regression_chosen")
        self.verticalLayout_8.addWidget(self.label_chosen_multy)
        self.label_y_multy_regression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_y_multy_regression.sizePolicy().hasHeightForWidth())
        self.label_y_multy_regression.setSizePolicy(size_policy)
        self.label_y_multy_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_y_multy_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_y_multy_regression.setFont(font)
        self.label_y_multy_regression.setObjectName("label_y_multy_regression")
        self.verticalLayout_8.addWidget(self.label_y_multy_regression)
        self.comboBox_y_multy_regression = QtWidgets.QComboBox(self)
        self.comboBox_y_multy_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_y_multy_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_y_multy_regression.setObjectName("comboBox_y_multy_regression")

        self.verticalLayout_8.addWidget(self.comboBox_y_multy_regression)
        self.label_predict_multy_regression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_predict_multy_regression.sizePolicy().hasHeightForWidth())
        self.label_predict_multy_regression.setSizePolicy(size_policy)
        self.label_predict_multy_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_predict_multy_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_predict_multy_regression.setFont(font)
        self.label_predict_multy_regression.setObjectName("label_predict_multy_regression")
        self.verticalLayout_8.addWidget(self.label_predict_multy_regression)
        self.lineEdit_x_multy_regression = QtWidgets.QLineEdit(self)
        self.lineEdit_x_multy_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_x_multy_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_x_multy_regression.setObjectName("lineEdit_x_multy_regression")
        self.verticalLayout_8.addWidget(self.lineEdit_x_multy_regression)
        self.result_predict_multy = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.result_predict_multy.sizePolicy().hasHeightForWidth())
        self.result_predict_multy.setSizePolicy(size_policy)
        self.result_predict_multy.setMinimumSize(QtCore.QSize(0, 30))
        self.result_predict_multy.setMaximumSize(QtCore.QSize(16777215, 30))
        self.result_predict_multy.setFont(font)
        self.result_predict_multy.setObjectName("result_multy_regression")
        self.verticalLayout_8.addWidget(self.result_predict_multy)
        self.btn_predict_multy_regression = QtWidgets.QPushButton(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.btn_predict_multy_regression.sizePolicy().hasHeightForWidth())
        self.btn_predict_multy_regression.setSizePolicy(size_policy)
        self.btn_predict_multy_regression.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_predict_multy_regression.setMaximumSize(QtCore.QSize(200, 50))
        self.btn_predict_multy_regression.setFont(font)
        self.btn_predict_multy_regression.setStyleSheet(stl_btn)
        self.btn_predict_multy_regression.setObjectName("btn_predict_multy_regression")
        self.verticalLayout_8.addWidget(self.btn_predict_multy_regression)
        self.line_4 = QtWidgets.QFrame(self, flags=QtCore.Qt.Widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_8.addWidget(self.line_4)
        self.result_multy_regression_text = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.result_multy_regression_text.sizePolicy().hasHeightForWidth())
        self.result_multy_regression_text.setSizePolicy(size_policy)
        self.result_multy_regression_text.setMinimumSize(QtCore.QSize(0, 30))
        self.result_multy_regression_text.setMaximumSize(QtCore.QSize(16777215, 30))
        self.result_multy_regression_text.setFont(font)
        self.result_multy_regression_text.setObjectName("result_predict")
        self.verticalLayout_8.addWidget(self.result_multy_regression_text)
        self.line_3 = QtWidgets.QFrame(self, flags=QtCore.Qt.Widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_8.addWidget(self.line_3)
        self.equation_multy_regression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.equation_multy_regression.sizePolicy().hasHeightForWidth())
        self.equation_multy_regression.setSizePolicy(size_policy)
        self.equation_multy_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.equation_multy_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.equation_multy_regression.setFont(font)
        self.equation_multy_regression.setObjectName("equation_multy_regression")
        self.verticalLayout_8.addWidget(self.equation_multy_regression)
        self.b0_multy_regression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.b0_multy_regression.sizePolicy().hasHeightForWidth())
        self.b0_multy_regression.setSizePolicy(size_policy)
        self.b0_multy_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.b0_multy_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.b0_multy_regression.setFont(font)
        self.b0_multy_regression.setObjectName("b0_multy_regression")
        self.verticalLayout_8.addWidget(self.b0_multy_regression)
        self.r2_multy_regression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.r2_multy_regression.sizePolicy().hasHeightForWidth())
        self.r2_multy_regression.setSizePolicy(size_policy)
        self.r2_multy_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.r2_multy_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.r2_multy_regression.setFont(font)
        self.r2_multy_regression.setObjectName("r2_multy_regression")
        self.verticalLayout_8.addWidget(self.r2_multy_regression)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.frame = QtWidgets.QFrame(self, flags=QtCore.Qt.Widget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(size_policy)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4.addWidget(self.frame, alignment=QtCore.Qt.AlignRight)
