from PyQt5 import QtCore, QtGui, QtWidgets

from Interface.CheckCombobox import CheckCombobox


class PageCrossValidation(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_choose_x_CrossValidation = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_CrossValidation.sizePolicy().hasHeightForWidth())
        self.label_choose_x_CrossValidation.setSizePolicy(size_policy)
        self.label_choose_x_CrossValidation.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_x_CrossValidation.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_x_CrossValidation.setFont(font)
        self.label_choose_x_CrossValidation.setObjectName("label_choose_x_CrossValidation")
        self.verticalLayout_18.addWidget(self.label_choose_x_CrossValidation)
        self.combobox_x_CrossValidation = CheckCombobox()

        self.verticalLayout_18.addWidget(self.combobox_x_CrossValidation)
        self.chosen_x_CrossValidation = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.chosen_x_CrossValidation.sizePolicy().hasHeightForWidth())
        self.chosen_x_CrossValidation.setSizePolicy(size_policy)
        self.chosen_x_CrossValidation.setMinimumSize(QtCore.QSize(0, 60))
        self.chosen_x_CrossValidation.setMaximumSize(QtCore.QSize(16777215, 60))
        self.chosen_x_CrossValidation.setFont(font)
        self.chosen_x_CrossValidation.setObjectName("chosen_x_CrossValidation")
        self.verticalLayout_18.addWidget(self.chosen_x_CrossValidation)
        self.label_choose_y_CrossValidation = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_CrossValidation.sizePolicy().hasHeightForWidth())
        self.label_choose_y_CrossValidation.setSizePolicy(size_policy)
        self.label_choose_y_CrossValidation.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_y_CrossValidation.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_y_CrossValidation.setFont(font)
        self.label_choose_y_CrossValidation.setObjectName("label_choose_y_CrossValidation")
        self.verticalLayout_18.addWidget(self.label_choose_y_CrossValidation)
        self.comboBox_y_CrossValidation = QtWidgets.QComboBox(self)
        self.comboBox_y_CrossValidation.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_y_CrossValidation.setObjectName("comboBox_y_CrossValidation")

        self.verticalLayout_18.addWidget(self.comboBox_y_CrossValidation)
        self.btn_find_CrossValidation = QtWidgets.QPushButton(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.btn_find_CrossValidation.sizePolicy().hasHeightForWidth())
        self.btn_find_CrossValidation.setSizePolicy(size_policy)
        self.btn_find_CrossValidation.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_find_CrossValidation.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_find_CrossValidation.setFont(font)
        self.btn_find_CrossValidation.setStyleSheet(stl_btn)
        self.btn_find_CrossValidation.setObjectName("btn_find_CrossValidation")
        self.verticalLayout_18.addWidget(self.btn_find_CrossValidation)
        self.horizontalLayout_9.addLayout(self.verticalLayout_18)
        self.tableWidget_CrossValidation = QtWidgets.QTableWidget(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.tableWidget_CrossValidation.sizePolicy().hasHeightForWidth())
        self.tableWidget_CrossValidation.setSizePolicy(size_policy)
        self.tableWidget_CrossValidation.setObjectName("tableWidget_CrossValidation")
        self.tableWidget_CrossValidation.setColumnCount(0)
        self.tableWidget_CrossValidation.setRowCount(0)
        self.horizontalLayout_9.addWidget(self.tableWidget_CrossValidation)
