from PyQt5 import QtCore, QtGui, QtWidgets

from Interface.CheckCombobox import CheckCombobox
from Interface.MplCanvas import MplCanvas


class PageLogisticRegression(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_choose_x_LogisticRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_LogisticRegression.sizePolicy().hasHeightForWidth())
        self.label_choose_x_LogisticRegression.setSizePolicy(size_policy)
        self.label_choose_x_LogisticRegression.setMinimumSize(QtCore.QSize(0, 40))
        self.label_choose_x_LogisticRegression.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_choose_x_LogisticRegression.setFont(font)
        self.label_choose_x_LogisticRegression.setObjectName("label_choose_x_LogisticRegression")
        self.verticalLayout_17.addWidget(self.label_choose_x_LogisticRegression)
        self.combobox_x_LogisticRegression = CheckCombobox()

        self.verticalLayout_17.addWidget(self.combobox_x_LogisticRegression)
        self.chosen_x_LogisticRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.chosen_x_LogisticRegression.sizePolicy().hasHeightForWidth())
        self.chosen_x_LogisticRegression.setSizePolicy(size_policy)
        self.chosen_x_LogisticRegression.setMinimumSize(QtCore.QSize(0, 40))
        self.chosen_x_LogisticRegression.setFont(font)
        self.chosen_x_LogisticRegression.setObjectName("chosen_x_LogisticRegression")
        self.verticalLayout_17.addWidget(self.chosen_x_LogisticRegression)
        self.label_choose_y_LogisticRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_LogisticRegression.sizePolicy().hasHeightForWidth())
        self.label_choose_y_LogisticRegression.setSizePolicy(size_policy)
        self.label_choose_y_LogisticRegression.setMinimumSize(QtCore.QSize(0, 40))
        self.label_choose_y_LogisticRegression.setFont(font)
        self.label_choose_y_LogisticRegression.setObjectName("label_choose_y_LogisticRegression")
        self.verticalLayout_17.addWidget(self.label_choose_y_LogisticRegression)
        self.comboBox_y_LogisticRegression = QtWidgets.QComboBox(self)
        self.comboBox_y_LogisticRegression.setObjectName("comboBox_y_LogisticRegression")

        self.verticalLayout_17.addWidget(self.comboBox_y_LogisticRegression)
        self.label_data_predict_LogisticRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_data_predict_LogisticRegression.sizePolicy().hasHeightForWidth())
        self.label_data_predict_LogisticRegression.setSizePolicy(size_policy)
        self.label_data_predict_LogisticRegression.setMinimumSize(QtCore.QSize(0, 40))
        self.label_data_predict_LogisticRegression.setFont(font)
        self.label_data_predict_LogisticRegression.setObjectName("label_data_predict_LogisticRegression")
        self.verticalLayout_17.addWidget(self.label_data_predict_LogisticRegression)
        self.lineEdit_data_LogisticRegression = QtWidgets.QLineEdit(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_data_LogisticRegression.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_LogisticRegression.setSizePolicy(size_policy)
        self.lineEdit_data_LogisticRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_data_LogisticRegression.setObjectName("lineEdit_data_LogisticRegression")
        self.verticalLayout_17.addWidget(self.lineEdit_data_LogisticRegression)
        self.predict_LogisticRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.predict_LogisticRegression.sizePolicy().hasHeightForWidth())
        self.predict_LogisticRegression.setSizePolicy(size_policy)
        self.predict_LogisticRegression.setMinimumSize(QtCore.QSize(0, 40))
        self.predict_LogisticRegression.setMaximumSize(QtCore.QSize(16777215, 40))
        self.predict_LogisticRegression.setFont(font)
        self.predict_LogisticRegression.setObjectName("predict_LogisticRegression")
        self.verticalLayout_17.addWidget(self.predict_LogisticRegression)
        self.btn_predict_LogisticRegression = QtWidgets.QPushButton(self)
        self.btn_predict_LogisticRegression.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_predict_LogisticRegression.setFont(font)
        self.btn_predict_LogisticRegression.setStyleSheet(stl_btn)
        self.btn_predict_LogisticRegression.setObjectName("btn_predict_LogisticRegression")
        self.verticalLayout_17.addWidget(self.btn_predict_LogisticRegression)
        self.b0_LogisticRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.b0_LogisticRegression.sizePolicy().hasHeightForWidth())
        self.b0_LogisticRegression.setSizePolicy(size_policy)
        self.b0_LogisticRegression.setMinimumSize(QtCore.QSize(0, 40))
        self.b0_LogisticRegression.setFont(font)
        self.b0_LogisticRegression.setObjectName("b0_LogisticRegression")
        self.verticalLayout_17.addWidget(self.b0_LogisticRegression)
        self.coefficient_LogisticRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.coefficient_LogisticRegression.sizePolicy().hasHeightForWidth())
        self.coefficient_LogisticRegression.setSizePolicy(size_policy)
        self.coefficient_LogisticRegression.setMinimumSize(QtCore.QSize(0, 60))
        self.coefficient_LogisticRegression.setFont(font)
        self.coefficient_LogisticRegression.setObjectName("coefficient_LogisticRegression")
        self.verticalLayout_17.addWidget(self.coefficient_LogisticRegression)
        self.score_LogisticRegression = QtWidgets.QLabel(self)
        self.score_LogisticRegression.setFont(font)
        self.score_LogisticRegression.setObjectName("score_LogisticRegression")
        self.verticalLayout_17.addWidget(self.score_LogisticRegression)
        self.horizontalLayout_8.addLayout(self.verticalLayout_17)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.canvas_LogisticRegression = MplCanvas(self)
        self.verticalLayout_16.addWidget(self.canvas_LogisticRegression)
        self.canvas_logic_matrix = MplCanvas(self)
        self.verticalLayout_16.addWidget(self.canvas_logic_matrix)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
