from PyQt5 import QtCore, QtWidgets

from Interface.MplCanvas import MplCanvas


class PageLinearRegression(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.x_label = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.x_label.sizePolicy().hasHeightForWidth())
        self.x_label.setSizePolicy(size_policy)
        self.x_label.setMinimumSize(QtCore.QSize(0, 30))
        self.x_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")
        self.verticalLayout_6.addWidget(self.x_label)
        self.comboBox_x = QtWidgets.QComboBox(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.comboBox_x.sizePolicy().hasHeightForWidth())
        self.comboBox_x.setSizePolicy(size_policy)
        self.comboBox_x.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBox_x.setMaximumSize(QtCore.QSize(200, 30))
        self.comboBox_x.setObjectName("comboBox_x")

        self.verticalLayout_6.addWidget(self.comboBox_x)
        self.y_label = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.y_label.sizePolicy().hasHeightForWidth())
        self.y_label.setSizePolicy(size_policy)
        self.y_label.setMinimumSize(QtCore.QSize(0, 30))
        self.y_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")
        self.verticalLayout_6.addWidget(self.y_label)
        self.comboBox_y = QtWidgets.QComboBox(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.comboBox_y.sizePolicy().hasHeightForWidth())
        self.comboBox_y.setSizePolicy(size_policy)
        self.comboBox_y.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBox_y.setMaximumSize(QtCore.QSize(200, 30))
        self.comboBox_y.setObjectName("comboBox_y")
        # self.comboBox_y.activated.connect(self.chosen)
        self.verticalLayout_6.addWidget(self.comboBox_y)
        self.label_predict_linear = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_predict_linear.sizePolicy().hasHeightForWidth())
        self.label_predict_linear.setSizePolicy(size_policy)
        self.label_predict_linear.setMinimumSize(QtCore.QSize(0, 30))
        self.label_predict_linear.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_predict_linear.setFont(font)
        self.label_predict_linear.setObjectName("label_predict_linear")
        self.verticalLayout_6.addWidget(self.label_predict_linear)
        self.lin_reg_predict = QtWidgets.QLineEdit(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lin_reg_predict.sizePolicy().hasHeightForWidth())
        self.lin_reg_predict.setSizePolicy(size_policy)
        self.lin_reg_predict.setObjectName("lin_reg_predict")
        self.verticalLayout_6.addWidget(self.lin_reg_predict)
        self.predict_btn = QtWidgets.QPushButton(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.predict_btn.sizePolicy().hasHeightForWidth())
        self.predict_btn.setSizePolicy(size_policy)
        self.predict_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.predict_btn.setMaximumSize(QtCore.QSize(120, 50))
        self.predict_btn.setFont(font)
        self.predict_btn.setStyleSheet(stl_btn)
        self.predict_btn.setObjectName("predict_btn")
        self.verticalLayout_6.addWidget(self.predict_btn)
        self.label_result = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_result.sizePolicy().hasHeightForWidth())
        self.label_result.setSizePolicy(size_policy)
        self.label_result.setMinimumSize(QtCore.QSize(0, 30))
        self.label_result.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_6.addWidget(self.label_result)
        self.line_2 = QtWidgets.QFrame(self, flags=QtCore.Qt.Widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(size_policy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(self, flags=QtCore.Qt.Widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.equation = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.equation.sizePolicy().hasHeightForWidth())
        self.equation.setSizePolicy(size_policy)
        self.equation.setMinimumSize(QtCore.QSize(0, 30))
        self.equation.setMaximumSize(QtCore.QSize(16777215, 30))
        self.equation.setFont(font)
        self.equation.setObjectName("equation")
        self.verticalLayout_6.addWidget(self.equation)
        self.label_b0 = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_b0.sizePolicy().hasHeightForWidth())
        self.label_b0.setSizePolicy(size_policy)
        self.label_b0.setMinimumSize(QtCore.QSize(0, 30))
        self.label_b0.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_b0.setFont(font)
        self.label_b0.setObjectName("label_b0")
        self.verticalLayout_6.addWidget(self.label_b0)
        self.label_b1 = QtWidgets.QLabel(self)
        self.label_b1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_b1.setFont(font)
        self.label_b1.setObjectName("label_b1")
        self.verticalLayout_6.addWidget(self.label_b1)
        self.label_mse = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_mse.sizePolicy().hasHeightForWidth())
        self.label_mse.setSizePolicy(size_policy)
        self.label_mse.setMinimumSize(QtCore.QSize(0, 30))
        self.label_mse.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_mse.setFont(font)
        self.label_mse.setObjectName("label_mse")
        self.verticalLayout_6.addWidget(self.label_mse)
        self.label_r2 = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_r2.sizePolicy().hasHeightForWidth())
        self.label_r2.setSizePolicy(size_policy)
        self.label_r2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_r2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_r2.setFont(font)
        self.label_r2.setObjectName("label_r2")
        self.verticalLayout_6.addWidget(self.label_r2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.canvas1 = MplCanvas(self)
        self.horizontalLayout_3.addWidget(self.canvas1)
