from PyQt5 import QtCore, QtGui, QtWidgets

from Interface.CheckCombobox import CheckCombobox
from Interface.MplCanvas import MplCanvas


class PageRegressionTree(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_13")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")

        self.label_best_parameters_regression_tree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_best_parameters_regression_tree.sizePolicy().hasHeightForWidth())
        self.label_best_parameters_regression_tree.setSizePolicy(size_policy)
        self.label_best_parameters_regression_tree.setMinimumSize(QtCore.QSize(0, 60))
        self.label_best_parameters_regression_tree.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_best_parameters_regression_tree.setFont(font)
        self.label_best_parameters_regression_tree.setObjectName("label_best_parameters_regression_tree ")
        self.verticalLayout_37.addWidget(self.label_best_parameters_regression_tree)

        self.label_x_regression_tree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_x_regression_tree.sizePolicy().hasHeightForWidth())
        self.label_x_regression_tree.setSizePolicy(size_policy)
        self.label_x_regression_tree.setMinimumSize(QtCore.QSize(0, 60))
        self.label_x_regression_tree.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_x_regression_tree.setFont(font)
        self.label_x_regression_tree.setObjectName("label_x_regression_tree")
        self.verticalLayout_37.addWidget(self.label_x_regression_tree)
        self.combobox_x_regression_tree = CheckCombobox()

        self.verticalLayout_37.addWidget(self.combobox_x_regression_tree)
        self.label_chosen_x_regression_tree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_chosen_x_regression_tree.sizePolicy().hasHeightForWidth())
        self.label_chosen_x_regression_tree.setSizePolicy(size_policy)
        self.label_chosen_x_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.label_chosen_x_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_chosen_x_regression_tree.setFont(font)
        self.label_chosen_x_regression_tree.setObjectName("label_x_regression_tree_choose")
        self.verticalLayout_37.addWidget(self.label_chosen_x_regression_tree)
        self.label_y_regression_tree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_y_regression_tree.sizePolicy().hasHeightForWidth())
        self.label_y_regression_tree.setSizePolicy(size_policy)
        self.label_y_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.label_y_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_y_regression_tree.setFont(font)
        self.label_y_regression_tree.setObjectName("label_y_regression_tree")
        self.verticalLayout_37.addWidget(self.label_y_regression_tree)
        self.comboBox_y_regression_tree = QtWidgets.QComboBox(self)
        self.comboBox_y_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_y_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_y_regression_tree.setObjectName("comboBox_y_regression_tree")

        self.verticalLayout_37.addWidget(self.comboBox_y_regression_tree)

        self.label_regression_tree_depth = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_regression_tree_depth.sizePolicy().hasHeightForWidth())
        self.label_regression_tree_depth.setSizePolicy(size_policy)
        self.label_regression_tree_depth.setMinimumSize(QtCore.QSize(0, 30))
        self.label_regression_tree_depth.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_regression_tree_depth.setFont(font)
        self.label_regression_tree_depth.setObjectName("label_regression_tree_depth")
        self.verticalLayout_37.addWidget(self.label_regression_tree_depth)
        self.lineEdit_depth_regression_tree = QtWidgets.QLineEdit(self)
        self.lineEdit_depth_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_depth_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_depth_regression_tree.setObjectName("lineEdit_depth_regression_tree")
        self.verticalLayout_37.addWidget(self.lineEdit_depth_regression_tree)

        self.label_regression_tree_split = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_regression_tree_split.sizePolicy().hasHeightForWidth())
        self.label_regression_tree_split.setSizePolicy(size_policy)
        self.label_regression_tree_split.setMinimumSize(QtCore.QSize(0, 30))
        self.label_regression_tree_split.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_regression_tree_split.setFont(font)
        self.label_regression_tree_split.setObjectName("label_regression_tree_split")
        self.verticalLayout_37.addWidget(self.label_regression_tree_split)
        self.lineEdit_regression_tree_split = QtWidgets.QLineEdit(self)
        self.lineEdit_regression_tree_split.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_regression_tree_split.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_regression_tree_split.setObjectName("lineEdit_regression_tree_split")
        self.verticalLayout_37.addWidget(self.lineEdit_regression_tree_split)

        self.label_regression_tree_leaf = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_regression_tree_leaf.sizePolicy().hasHeightForWidth())
        self.label_regression_tree_leaf.setSizePolicy(size_policy)
        self.label_regression_tree_leaf.setMinimumSize(QtCore.QSize(0, 30))
        self.label_regression_tree_leaf.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_regression_tree_leaf.setFont(font)
        self.label_regression_tree_leaf.setObjectName("label_regression_tree_leaf")
        self.verticalLayout_37.addWidget(self.label_regression_tree_leaf)
        self.lineEdit_regression_tree_leaf = QtWidgets.QLineEdit(self)
        self.lineEdit_regression_tree_leaf.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_regression_tree_leaf.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_regression_tree_leaf.setObjectName("lineEdit_regression_tree_leaf")
        self.verticalLayout_37.addWidget(self.lineEdit_regression_tree_leaf)

        self.label_predict_regression_tree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_predict_regression_tree.sizePolicy().hasHeightForWidth())
        self.label_predict_regression_tree.setSizePolicy(size_policy)
        self.label_predict_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.label_predict_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_predict_regression_tree.setFont(font)
        self.label_predict_regression_tree.setObjectName("label_predict_regression_tree")
        self.verticalLayout_37.addWidget(self.label_predict_regression_tree)
        self.lineEdit_x_regression_tree = QtWidgets.QLineEdit(self)
        self.lineEdit_x_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_x_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_x_regression_tree.setObjectName("lineEdit_x_regression_tree")
        self.verticalLayout_37.addWidget(self.lineEdit_x_regression_tree)
        self.result_predict_regression_tree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.result_predict_regression_tree.sizePolicy().hasHeightForWidth())
        self.result_predict_regression_tree.setSizePolicy(size_policy)
        self.result_predict_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.result_predict_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.result_predict_regression_tree.setFont(font)
        self.result_predict_regression_tree.setObjectName("result_regression_tree")
        self.verticalLayout_37.addWidget(self.result_predict_regression_tree)
        self.btn_predict_regression_tree = QtWidgets.QPushButton(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.btn_predict_regression_tree.sizePolicy().hasHeightForWidth())
        self.btn_predict_regression_tree.setSizePolicy(size_policy)
        self.btn_predict_regression_tree.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_predict_regression_tree.setMaximumSize(QtCore.QSize(200, 50))
        self.btn_predict_regression_tree.setFont(font)
        self.btn_predict_regression_tree.setStyleSheet(stl_btn)
        self.btn_predict_regression_tree.setObjectName("btn_predict_multy_regression")
        self.verticalLayout_37.addWidget(self.btn_predict_regression_tree)
        self.line_5 = QtWidgets.QFrame(self, flags=QtCore.Qt.Widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_37.addWidget(self.line_5)
        self.result_regression_tree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.result_regression_tree.sizePolicy().hasHeightForWidth())
        self.result_regression_tree.setSizePolicy(size_policy)
        self.result_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.result_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.result_regression_tree.setFont(font)
        self.result_regression_tree.setObjectName("result_predict_regression_tree")
        self.verticalLayout_37.addWidget(self.result_regression_tree)
        self.line_6 = QtWidgets.QFrame(self, flags=QtCore.Qt.Widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_37.addWidget(self.line_6)
        self.mse_regression_tree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.mse_regression_tree.sizePolicy().hasHeightForWidth())
        self.mse_regression_tree.setSizePolicy(size_policy)
        self.mse_regression_tree.setMinimumSize(QtCore.QSize(0, 30))
        self.mse_regression_tree.setMaximumSize(QtCore.QSize(16777215, 30))
        self.mse_regression_tree.setFont(font)
        self.mse_regression_tree.setObjectName("mse_regression_tree")
        self.verticalLayout_37.addWidget(self.mse_regression_tree)
        self.horizontalLayout_34.addLayout(self.verticalLayout_37)
        self.canvas_regression_tree = MplCanvas(self)
        self.horizontalLayout_34.addWidget(self.canvas_regression_tree)
