from PyQt5 import QtCore, QtWidgets

from Interface.CheckCombobox import CheckCombobox
from Interface.MplCanvas import MplCanvas


class PageKNNRegression(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(size_policy)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget(flags=QtCore.Qt.Widget)
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_x_knn_regression = QtWidgets.QLabel(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_x_knn_regression.sizePolicy().hasHeightForWidth())
        self.label_x_knn_regression.setSizePolicy(size_policy)
        self.label_x_knn_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_x_knn_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_x_knn_regression.setFont(font)
        self.label_x_knn_regression.setObjectName("label")
        self.verticalLayout_25.addWidget(self.label_x_knn_regression)
        self.combobox_x_knnRegression = CheckCombobox()
        self.verticalLayout_25.addWidget(self.combobox_x_knnRegression)
        self.label_chosen_x_knnRegression = QtWidgets.QLabel(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_chosen_x_knnRegression.sizePolicy().hasHeightForWidth())
        self.label_chosen_x_knnRegression.setSizePolicy(size_policy)
        self.label_chosen_x_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_chosen_x_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_chosen_x_knnRegression.setFont(font)
        self.label_chosen_x_knnRegression.setObjectName("label_chosen_x_knnRegression")
        self.verticalLayout_25.addWidget(self.label_chosen_x_knnRegression)
        self.label_y_knn_regression = QtWidgets.QLabel(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_y_knn_regression.sizePolicy().hasHeightForWidth())
        self.label_y_knn_regression.setSizePolicy(size_policy)
        self.label_y_knn_regression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_y_knn_regression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_y_knn_regression.setFont(font)
        self.label_y_knn_regression.setObjectName("label_3")
        self.verticalLayout_25.addWidget(self.label_y_knn_regression)
        self.comboBox_Y_knnRegression = QtWidgets.QComboBox(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.comboBox_Y_knnRegression.sizePolicy().hasHeightForWidth())
        self.comboBox_Y_knnRegression.setSizePolicy(size_policy)
        self.comboBox_Y_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_Y_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_Y_knnRegression.setObjectName("comboBox_Y_knnRegression")

        self.verticalLayout_25.addWidget(self.comboBox_Y_knnRegression)
        self.label_k = QtWidgets.QLabel(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_k.sizePolicy().hasHeightForWidth())
        self.label_k.setSizePolicy(size_policy)
        self.label_k.setMinimumSize(QtCore.QSize(0, 30))
        self.label_k.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_k.setFont(font)
        self.label_k.setObjectName("label_4")
        self.verticalLayout_25.addWidget(self.label_k)
        self.lineEdit_num_neigh = QtWidgets.QLineEdit(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_num_neigh.sizePolicy().hasHeightForWidth())
        self.lineEdit_num_neigh.setSizePolicy(size_policy)
        self.lineEdit_num_neigh.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_num_neigh.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_num_neigh.setObjectName("lineEdit_num_neigh")
        self.verticalLayout_25.addWidget(self.lineEdit_num_neigh)
        self.label_data_predict_text = QtWidgets.QLabel(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_data_predict_text.sizePolicy().hasHeightForWidth())
        self.label_data_predict_text.setSizePolicy(size_policy)
        self.label_data_predict_text.setMinimumSize(QtCore.QSize(0, 30))
        self.label_data_predict_text.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_data_predict_text.setFont(font)
        self.label_data_predict_text.setObjectName("label_5")
        self.verticalLayout_25.addWidget(self.label_data_predict_text)
        self.lineEdit_data_predict = QtWidgets.QLineEdit(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_data_predict.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_predict.setSizePolicy(size_policy)
        self.lineEdit_data_predict.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_data_predict.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_data_predict.setObjectName("lineEdit_data_predict")
        self.verticalLayout_25.addWidget(self.lineEdit_data_predict)
        self.label_result_knnRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_result_knnRegression.sizePolicy().hasHeightForWidth())
        self.label_result_knnRegression.setSizePolicy(size_policy)
        self.label_result_knnRegression.setMinimumSize(QtCore.QSize(0, 25))
        self.label_result_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_result_knnRegression.setFont(font)
        self.label_result_knnRegression.setObjectName("label_result_knnRegression")
        self.verticalLayout_25.addWidget(self.label_result_knnRegression)
        self.btn_predict_knnRegression = QtWidgets.QPushButton(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.btn_predict_knnRegression.sizePolicy().hasHeightForWidth())
        self.btn_predict_knnRegression.setSizePolicy(size_policy)
        self.btn_predict_knnRegression.setMinimumSize(QtCore.QSize(120, 50))
        self.btn_predict_knnRegression.setMaximumSize(QtCore.QSize(120, 50))
        self.btn_predict_knnRegression.setFont(font)
        self.btn_predict_knnRegression.setStyleSheet(stl_btn)
        self.btn_predict_knnRegression.setObjectName("btn_predict_knnRegression")
        self.verticalLayout_25.addWidget(self.btn_predict_knnRegression)
        self.label_r2_knnRegression = QtWidgets.QLabel(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_r2_knnRegression.sizePolicy().hasHeightForWidth())
        self.label_r2_knnRegression.setSizePolicy(size_policy)
        self.label_r2_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_r2_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_r2_knnRegression.setFont(font)
        self.label_r2_knnRegression.setObjectName("label_r2_knnRegression")
        self.verticalLayout_25.addWidget(self.label_r2_knnRegression)
        self.label_mae_knnRegression = QtWidgets.QLabel(self.tab_5)
        self.label_mae_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_mae_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_mae_knnRegression.setFont(font)
        self.label_mae_knnRegression.setObjectName("label_mae_knnRegression")
        self.verticalLayout_25.addWidget(self.label_mae_knnRegression)
        self.label_mse_knnRegression = QtWidgets.QLabel(self.tab_5)
        self.label_mse_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_mse_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_mse_knnRegression.setFont(font)
        self.label_mse_knnRegression.setObjectName("label_mse_knnRegression")
        self.verticalLayout_25.addWidget(self.label_mse_knnRegression)
        self.label_rmse_knnRegression = QtWidgets.QLabel(self.tab_5)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_rmse_knnRegression.sizePolicy().hasHeightForWidth())
        self.label_rmse_knnRegression.setSizePolicy(size_policy)
        self.label_rmse_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_rmse_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_rmse_knnRegression.setFont(font)
        self.label_rmse_knnRegression.setObjectName("label_rmse_knnRegression")
        self.verticalLayout_25.addWidget(self.label_rmse_knnRegression)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget(flags=QtCore.Qt.Widget)
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_min_k = QtWidgets.QLabel(self.tab_6)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_min_k.sizePolicy().hasHeightForWidth())
        self.label_min_k.setSizePolicy(size_policy)
        self.label_min_k.setMinimumSize(QtCore.QSize(0, 30))
        self.label_min_k.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_min_k.setFont(font)
        self.label_min_k.setObjectName("label_10")
        self.verticalLayout_27.addWidget(self.label_min_k)
        self.lineEdit_min_neigh = QtWidgets.QLineEdit(self.tab_6)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_min_neigh.sizePolicy().hasHeightForWidth())
        self.lineEdit_min_neigh.setSizePolicy(size_policy)
        self.lineEdit_min_neigh.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_min_neigh.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_min_neigh.setObjectName("lineEdit_min_neigh")
        self.verticalLayout_27.addWidget(self.lineEdit_min_neigh)
        self.label_max_k = QtWidgets.QLabel(self.tab_6)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_max_k.sizePolicy().hasHeightForWidth())
        self.label_max_k.setSizePolicy(size_policy)
        self.label_max_k.setMinimumSize(QtCore.QSize(0, 30))
        self.label_max_k.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_max_k.setFont(font)
        self.label_max_k.setObjectName("label_11")
        self.verticalLayout_27.addWidget(self.label_max_k)
        self.lineEdit_max_neigh = QtWidgets.QLineEdit(self.tab_6)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_max_neigh.sizePolicy().hasHeightForWidth())
        self.lineEdit_max_neigh.setSizePolicy(size_policy)
        self.lineEdit_max_neigh.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_max_neigh.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_max_neigh.setObjectName("lineEdit_max_neigh")
        self.verticalLayout_27.addWidget(self.lineEdit_max_neigh)
        self.btn_find_neigh_knnRegression = QtWidgets.QPushButton(self.tab_6)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.btn_find_neigh_knnRegression.sizePolicy().hasHeightForWidth())
        self.btn_find_neigh_knnRegression.setSizePolicy(size_policy)
        self.btn_find_neigh_knnRegression.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_find_neigh_knnRegression.setMaximumSize(QtCore.QSize(100, 40))
        self.btn_find_neigh_knnRegression.setFont(font)
        self.btn_find_neigh_knnRegression.setStyleSheet(stl_btn)
        self.btn_find_neigh_knnRegression.setObjectName("btn_find_neigh_knnRegression")
        self.verticalLayout_27.addWidget(self.btn_find_neigh_knnRegression)
        self.label_result_neigh = QtWidgets.QLabel(self.tab_6)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_result_neigh.sizePolicy().hasHeightForWidth())
        self.label_result_neigh.setSizePolicy(size_policy)
        self.label_result_neigh.setMinimumSize(QtCore.QSize(0, 30))
        self.label_result_neigh.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_result_neigh.setFont(font)
        self.label_result_neigh.setObjectName("label_result_neigh")
        self.verticalLayout_27.addWidget(self.label_result_neigh)
        self.label_r2best_knnRegression = QtWidgets.QLabel(self.tab_6)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_r2best_knnRegression.sizePolicy().hasHeightForWidth())
        self.label_r2best_knnRegression.setSizePolicy(size_policy)
        self.label_r2best_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_r2best_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_r2best_knnRegression.setFont(font)
        self.label_r2best_knnRegression.setObjectName("label_r2best_knnRegression")
        self.verticalLayout_27.addWidget(self.label_r2best_knnRegression)
        self.label_mae_best_knnRegression = QtWidgets.QLabel(self.tab_6)
        self.label_mae_best_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_mae_best_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_mae_best_knnRegression.setFont(font)
        self.label_mae_best_knnRegression.setObjectName("label_mae_best_knnRegression")
        self.verticalLayout_27.addWidget(self.label_mae_best_knnRegression)
        self.label_mse_best_knnRegression = QtWidgets.QLabel(self.tab_6)
        self.label_mse_best_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_mse_best_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_mse_best_knnRegression.setFont(font)
        self.label_mse_best_knnRegression.setObjectName("label_mse_best_knnRegression")
        self.verticalLayout_27.addWidget(self.label_mse_best_knnRegression)
        self.label_rmse_best_knnRegression = QtWidgets.QLabel(self.tab_6)
        self.label_rmse_best_knnRegression.setMinimumSize(QtCore.QSize(0, 30))
        self.label_rmse_best_knnRegression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_rmse_best_knnRegression.setFont(font)
        self.label_rmse_best_knnRegression.setObjectName("label_rmse_best_knnRegression")
        self.verticalLayout_27.addWidget(self.label_rmse_best_knnRegression)
        self.horizontalLayout_15.addLayout(self.verticalLayout_27)
        self.canvas_knnRegression = MplCanvas(self)
        self.horizontalLayout_15.addWidget(self.canvas_knnRegression)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.horizontalLayout_5.addWidget(self.tabWidget_2)
