from PyQt5 import QtCore, QtWidgets

from Interface.MplCanvas import MplCanvas


class PagePolynomialRegression(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_choose_x_PolynomialRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_PolynomialRegression.sizePolicy().hasHeightForWidth())
        self.label_choose_x_PolynomialRegression.setSizePolicy(size_policy)
        self.label_choose_x_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_x_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_x_PolynomialRegression.setFont(font)
        self.label_choose_x_PolynomialRegression.setObjectName("label_choose_x_PolynomialRegression")
        self.verticalLayout_22.addWidget(self.label_choose_x_PolynomialRegression)
        self.comboBox_x_PolynomialRegression = QtWidgets.QComboBox(self)
        self.comboBox_x_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_x_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBox_x_PolynomialRegression.setObjectName("comboBox_x_PolynomialRegression")

        self.verticalLayout_22.addWidget(self.comboBox_x_PolynomialRegression)
        self.label_choose_y_PolynomialRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_PolynomialRegression.sizePolicy().hasHeightForWidth())
        self.label_choose_y_PolynomialRegression.setSizePolicy(size_policy)
        self.label_choose_y_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 60))
        self.label_choose_y_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_choose_y_PolynomialRegression.setFont(font)
        self.label_choose_y_PolynomialRegression.setObjectName("label_choose_y_PolynomialRegression")
        self.verticalLayout_22.addWidget(self.label_choose_y_PolynomialRegression)
        self.comboBox_y_PolynomialRegression = QtWidgets.QComboBox(self)
        self.comboBox_y_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_y_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBox_y_PolynomialRegression.setObjectName("comboBox_y_PolynomialRegression")

        self.verticalLayout_22.addWidget(self.comboBox_y_PolynomialRegression)
        self.label_degree = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_degree.sizePolicy().hasHeightForWidth())
        self.label_degree.setSizePolicy(size_policy)
        self.label_degree.setMinimumSize(QtCore.QSize(0, 60))
        self.label_degree.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_degree.setFont(font)
        self.label_degree.setObjectName("label_degree")
        self.verticalLayout_22.addWidget(self.label_degree)
        self.lineEdit_degree = QtWidgets.QLineEdit(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_degree.sizePolicy().hasHeightForWidth())
        self.lineEdit_degree.setSizePolicy(size_policy)
        self.lineEdit_degree.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_degree.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_degree.setObjectName("lineEdit_degree")
        self.verticalLayout_22.addWidget(self.lineEdit_degree)
        self.label_data_predict_PolynomialRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_data_predict_PolynomialRegression.sizePolicy().hasHeightForWidth())
        self.label_data_predict_PolynomialRegression.setSizePolicy(size_policy)
        self.label_data_predict_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 60))
        self.label_data_predict_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_data_predict_PolynomialRegression.setFont(font)
        self.label_data_predict_PolynomialRegression.setObjectName("label_data_predict_PolynomialRegression")
        self.verticalLayout_22.addWidget(self.label_data_predict_PolynomialRegression)
        self.lineEdit_data_PolynomialRegression = QtWidgets.QLineEdit(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_data_PolynomialRegression.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_PolynomialRegression.setSizePolicy(size_policy)
        self.lineEdit_data_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_data_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_data_PolynomialRegression.setObjectName("lineEdit_data_PolynomialRegression")
        self.verticalLayout_22.addWidget(self.lineEdit_data_PolynomialRegression)
        self.label_result_PolynomialRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_result_PolynomialRegression.sizePolicy().hasHeightForWidth())
        self.label_result_PolynomialRegression.setSizePolicy(size_policy)
        self.label_result_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 60))
        self.label_result_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_result_PolynomialRegression.setFont(font)
        self.label_result_PolynomialRegression.setObjectName("label_result_PolynomialRegression")
        self.verticalLayout_22.addWidget(self.label_result_PolynomialRegression)
        self.btn_find_PolynomialRegression = QtWidgets.QPushButton(self)
        self.btn_find_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_find_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_find_PolynomialRegression.setFont(font)
        self.btn_find_PolynomialRegression.setStyleSheet(stl_btn)
        self.btn_find_PolynomialRegression.setObjectName("btn_find_PolynomialRegression")
        self.verticalLayout_22.addWidget(self.btn_find_PolynomialRegression)
        self.label_rmse_PolynomialRegression = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_rmse_PolynomialRegression.sizePolicy().hasHeightForWidth())
        self.label_rmse_PolynomialRegression.setSizePolicy(size_policy)
        self.label_rmse_PolynomialRegression.setMinimumSize(QtCore.QSize(0, 60))
        self.label_rmse_PolynomialRegression.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_rmse_PolynomialRegression.setFont(font)
        self.label_rmse_PolynomialRegression.setObjectName("label_rmse_PolynomialRegression")
        self.verticalLayout_22.addWidget(self.label_rmse_PolynomialRegression)
        self.horizontalLayout_12.addLayout(self.verticalLayout_22)
        self.canvas_PolynomialRegression = MplCanvas(self)
        self.horizontalLayout_12.addWidget(self.canvas_PolynomialRegression)
