from PyQt5 import QtCore, QtGui, QtWidgets

from Interface.CheckCombobox import CheckCombobox
from Interface.MplCanvas import MplCanvas


class PageLinearDiscriminant(QtWidgets.QWidget):
    def __init__(self, stl_btn, font):
        super().__init__()
        self.setObjectName("page_15")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_choose_x_LinearDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_x_LinearDiscriminant.sizePolicy().hasHeightForWidth())
        self.label_choose_x_LinearDiscriminant.setSizePolicy(size_policy)
        self.label_choose_x_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.label_choose_x_LinearDiscriminant.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_choose_x_LinearDiscriminant.setFont(font)
        self.label_choose_x_LinearDiscriminant.setObjectName("label_choose_x_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.label_choose_x_LinearDiscriminant)
        self.combobox_x_LinearDiscriminant = CheckCombobox()

        self.verticalLayout_40.addWidget(self.combobox_x_LinearDiscriminant)
        self.chosen_x_LinearDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.chosen_x_LinearDiscriminant.sizePolicy().hasHeightForWidth())
        self.chosen_x_LinearDiscriminant.setSizePolicy(size_policy)
        self.chosen_x_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.chosen_x_LinearDiscriminant.setFont(font)
        self.chosen_x_LinearDiscriminant.setObjectName("chosen_x_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.chosen_x_LinearDiscriminant)
        self.label_choose_y_LinearDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_choose_y_LinearDiscriminant.sizePolicy().hasHeightForWidth())
        self.label_choose_y_LinearDiscriminant.setSizePolicy(size_policy)
        self.label_choose_y_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.label_choose_y_LinearDiscriminant.setFont(font)
        self.label_choose_y_LinearDiscriminant.setObjectName("label_choose_y_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.label_choose_y_LinearDiscriminant)
        self.comboBox_y_LinearDiscriminant = QtWidgets.QComboBox(self)
        self.comboBox_y_LinearDiscriminant.setObjectName("comboBox_y_LinearDiscriminant")

        self.verticalLayout_40.addWidget(self.comboBox_y_LinearDiscriminant)
        self.label_data_predict_LinearDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label_data_predict_LinearDiscriminant.sizePolicy().hasHeightForWidth())
        self.label_data_predict_LinearDiscriminant.setSizePolicy(size_policy)
        self.label_data_predict_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.label_data_predict_LinearDiscriminant.setFont(font)
        self.label_data_predict_LinearDiscriminant.setObjectName("label_data_predict_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.label_data_predict_LinearDiscriminant)
        self.lineEdit_data_LinearDiscriminant = QtWidgets.QLineEdit(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lineEdit_data_LinearDiscriminant.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_LinearDiscriminant.setSizePolicy(size_policy)
        self.lineEdit_data_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_data_LinearDiscriminant.setObjectName("lineEdit_data_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.lineEdit_data_LinearDiscriminant)
        self.predict_LinearDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.predict_LinearDiscriminant.sizePolicy().hasHeightForWidth())
        self.predict_LinearDiscriminant.setSizePolicy(size_policy)
        self.predict_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.predict_LinearDiscriminant.setMaximumSize(QtCore.QSize(16777215, 40))
        self.predict_LinearDiscriminant.setFont(font)
        self.predict_LinearDiscriminant.setObjectName("predict_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.predict_LinearDiscriminant)
        self.btn_predict_LinearDiscriminant = QtWidgets.QPushButton(self)
        self.btn_predict_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_predict_LinearDiscriminant.setFont(font)
        self.btn_predict_LinearDiscriminant.setStyleSheet(stl_btn)
        self.btn_predict_LinearDiscriminant.setObjectName("btn_predict_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.btn_predict_LinearDiscriminant)
        self.report_LinearDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.report_LinearDiscriminant.sizePolicy().hasHeightForWidth())
        self.report_LinearDiscriminant.setSizePolicy(size_policy)
        self.report_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 40))
        self.report_LinearDiscriminant.setFont(font)
        self.report_LinearDiscriminant.setObjectName("report_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.report_LinearDiscriminant)
        self.accuracy_LinearDiscriminant = QtWidgets.QLabel(self)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.accuracy_LinearDiscriminant.sizePolicy().hasHeightForWidth())
        self.accuracy_LinearDiscriminant.setSizePolicy(size_policy)
        self.accuracy_LinearDiscriminant.setMinimumSize(QtCore.QSize(0, 60))
        self.accuracy_LinearDiscriminant.setFont(font)
        self.accuracy_LinearDiscriminant.setObjectName("accuracy_LinearDiscriminant")
        self.verticalLayout_40.addWidget(self.accuracy_LinearDiscriminant)
        self.horizontalLayout_36.addLayout(self.verticalLayout_40)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_16")
        self.canvas_LinearDiscriminant = MplCanvas(self)
        self.verticalLayout_41.addWidget(self.canvas_LinearDiscriminant)
        self.canvas_LinearDiscriminant_matrix = MplCanvas(self)
        self.verticalLayout_41.addWidget(self.canvas_LinearDiscriminant_matrix)
        self.horizontalLayout_36.addLayout(self.verticalLayout_41)
